permalink: /news/:year-:month/:title
plugins:
  - jekyll-feed
  - jekyll-redirect-from
collections:
  events:
    output: true
    permalink: /event/:year-:month/:title
  training-material:
defaults:
  -
    scope:
      type: "events"
    values:
      layout: "event"
      theme: "support"
      parent: "/support/training/events"