paginate: 10
paginate_path: /news/page:num
permalink: /news/:year-:month/:title
plugins:
  - jekyll-feed
  - jekyll-redirect-from
collections:
  events:
    output: true
    permalink: /event/:year-:month/:title
  resources:
  ambassadors:
    output: true
    permalink: /ambassador/:title
  team:
    output: true
    permalink: /team/:title
defaults:
  -
    scope:
      type: "events"
    values:
      layout: "event"
      theme: "support"
      parent: "/support/training/events"
  -
    scope:
      type: "ambassadors"
    values:
      layout: "ambassador"
      theme: "support"
      parent: "/support/ambassadors/current"
      markdown: false
  - scope:
      type: "team"
    values:
      layout: "team"